In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [59]:
data = pd.read_csv('Churn_Modelling.csv')
x = data.iloc[:,3:-1].values
y = data.iloc[:,-1].values

In [15]:
print('X = ',x)
print('\nY = ',y)

X =  [[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]

Y =  [1 0 1 ... 1 1 0]


In [60]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:,2] = lb.fit_transform(x[:,2])

In [24]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [61]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[1])], remainder = 'passthrough')
#x = np.array(ct.fit_transform(x))
x = np.array(ct.fit_transform(x))

In [62]:
print(x)
print(type(x))

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]
<class 'numpy.ndarray'>


In [34]:
np.shape(x)

(10000, 14)

In [65]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [37]:
np.shape(xtrain)

(8000, 14)

In [67]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtrain = sc.fit_transform(xtrain)
xtest = sc.transform(xtest)

## Building ANN

In [51]:
ann = tf.keras.models.Sequential()

In [52]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [53]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [54]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [55]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [68]:
ann.fit(xtrain,ytrain,batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 7s 3ms/step - loss: 0.5826 - accuracy: 0.7485
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4639 - accuracy: 0.7983
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4305 - accuracy: 0.8085
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4169 - accuracy: 0.8206
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4082 - accuracy: 0.8257
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8271
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3938 - accuracy: 0.8300
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3843 - accuracy: 0.8355
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3729 - accuracy: 0.8487
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3634 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3342 - accuracy: 0.8622
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3336 - accuracy: 0.8648
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3334 - accuracy: 0.8641
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3336 - accuracy: 0.8637
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3334 - accuracy: 0.8640
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3338 - accuracy: 0.8644
Epoch 87/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3333 - accuracy: 0.8643
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3333 - accuracy: 0.8645
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3332 - accuracy: 0.8649
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3331 - accuracy: 

In [69]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 295ms/step
[[False]]


In [71]:
y_pred = ann.predict(xtest)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), ytest.reshape(len(ytest),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(ytest, y_pred)
print(cm)
accuracy_score(ytest, y_pred)

[[1514   81]
 [ 193  212]]


0.863